// <auto-generated />
namespace DevDay.Quiz.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddSessions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSessions));
        
        string IMigrationMetadata.Id
        {
            get { return "201310072054047_AddSessions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
